import React, { useMemo } from 'react'
import { useSelector } from 'react-redux'

import HorizontalCategory from '../../../general/HorizontalCategory'

/**
 * HistoryCategory component
 * 
 * @param {object} props props object
 * @param {object} props.navigation Object generated by React Navigation
 * @param {number} props.maxContent Maximum amount of content to display in the category
 * 
 * @returns {JSX.Element} JSX component
 */
const HistoryCategory = ({
    navigation,
    maxContent = 10
}) => {
    /** 
     * We use the playlists content state here to update the component every time the user
     * listens to a track and it gets added to the history playlist
     * */
    const playlistsContent = useSelector(state => state.playlistsContent);
    const playlists = useSelector(state => state.playlists);
    const tracks = useSelector(state => state.tracks);

    const historyTracks = useMemo(() => {
        // TODO test if this works when user can add tracks
        const histPlaylist = playlists.find(pl => pl.title == "_HISTORY");

        if(histPlaylist) {
            const historyTrackIds = playlistsContent
                .filter(rel => rel.playlistId === histPlaylist.id)
                .map(rel => rel.trackId);

            return tracks.filter(track => historyTrackIds.includes(track.id));
        }

        return [];
    }, [playlistsContent]);

    return (
        <HorizontalCategory 
            navigation={navigation}
            title="Istoricul redărilor" 
            tracks={historyTracks}
            maxContent={maxContent}/>
    );
};

export default HistoryCategory
