import React, { useEffect } from 'react'
import { useSelector } from 'react-redux';

import HorizontalCategory from '../../../general/HorizontalCategory'


/**
 * TracksCategory component
 * 
 * @param {object} props props object
 * @param {object} props.navigation Object generated by React Navigation
 * @param {number} props.maxContent Maximum amount of content to display in the category
 * 
 * @returns {JSX.Element} JSX component
 */
const TracksCategory = ({
    navigation,
    maxContent = 10
}) => {
    const tracks = useSelector(state => state.tracks);

    return (
        <HorizontalCategory 
            navigation={navigation}
            title="Piesele tale" 
            tracks={tracks} 
            maxContent={maxContent}/>
    );
};


export default TracksCategory;